config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/creerreferent',           to: 'referents#new'
  get    '/creerorganisme',          to: 'organismes#new'
  get    '/creerorganismereferent',  to: 'organisme_referents#new'
  
  get    '/creerpointofservice',     to: 'point_of_services#new'
  get    '/creerunlocal',            to: 'un_locals#new'
  get    '/creerservice',            to: 'services#new'


  resources :organismes do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_org_ref, :ajouter_retirer_ref, :ajouter_retirer_point_service    
      get :organisme_id
    end
  end

  resources :organisme_referents do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_ref
    end
  end

  resources :referents do
    member do
      get :ajouter, :retirer
    end
  end

  resources :point_of_services do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_local
    end
  end

  resources :un_locals do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_service
    end
  end

  resources :services do
    member do
      get :ajouter, :retirer
    end
  end

  resources :account_activations,       only: [:edit]
  resources :password_resets,           only: [:new, :create, :edit, :update]
  resources :users

end

app/models/point_of_service.rb
class PointOfService < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  PROVINCES = %w[Quebec Ontario Colombie-Britanique Alberta Nouvelle-Ecosse Manitoba Saskatchewan Nouveau-Brunswick Terre-Neuve ].freeze

	validates :nom, :uniqueness => true
  validates :nom, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates_presence_of :nom, :tel, :fax, :email, :no_civique, :rue, :ville, :province, :code_postal

  before_save :downcase_email

  acts_as_follower
  acts_as_followable

  #**************************
  # Search
  #**************************
  def self.search(search)
    where("nom LIKE ?", "%#{search}%")
    where("email LIKE ?", "%#{search}%")
  end

  private

  #***********************************
  # Lettre minuscule email
  #***********************************
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/point_of_services_controller.rb
#**************************************************************
# CONTROLEUR POINT DE SERVICES
#**************************************************************
require 'openssl'
class PointOfServicesController < ApplicationController

  #**************************
  # Liste Point de Service
  #**************************
  def index
    @point_of_services = PointOfService.where(activated: true).paginate(page: params[:page])

    # Si une recherche est lancée
    if params[:search]
      @point_of_services = PointOfService.search(params[:search]).order("created_at DESC")
    else
      @point_of_services = PointOfService.all.order('created_at DESC')
    end
  end

  #******************************
  # Affiche info Point de Service
  #******************************
  def show
    @point_of_service = PointOfService.find(params[:id])

    # Permet d'afficher la liste des locaux sur la page qui affiche l'information Organisme
    @un_locals = UnLocal.where(activated: true).paginate(page: params[:page])
    @organismes = Organisme.where(activated: true).paginate(page: params[:page])

    # Permet de recuperer le nombre d'objets que le Point de Service possede
    qte_objets
  end

  #**************************
  # Quantité Objets
  #**************************
  def qte_objets

    # Permet d'afficher le nombre de locaux que possede le Point de Service
    @voslocaux = @point_of_service.follows_by_type('UnLocal').count 
  end 

  #**************************
  # Nouveau Point de Service
  #**************************
  def new
    @point_of_service = PointOfService.new
  end

  #**************************
  # Creer Point de Service
  #**************************
  def create
    @point_of_service = PointOfService.new(point_of_service_params)

    # Si l'utilisateur confirme la creation d'un organisme
    if @point_of_service.save
      @organisme = Organisme.find_by(id: @point_of_service.organismes_id)

      # Si l'ID entré n'es associé à aucun Organisme
      if @organisme == nil && @point_of_service.organismes_id != nil
        flash[:danger] = "Il n'existe pas d'Organisme avec l'ID #{@point_of_service.organismes_id}"
        render 'new'
      else
        
        # Si un ID Organisme a été entré
        if @point_of_service.organismes_id != nil
          @organisme.follow(@point_of_service)
        end  

        flash[:success] = "Point de service créé"
        redirect_to @point_of_service
      end  
    else
      render 'new'
    end
  end

  #**************************
  # Modifier Point de Service
  #**************************
  def edit
    @point_of_service = PointOfService.find(params[:id])
  end

  #*****************************
  # Mise a jour Point de Service
  #*****************************
  def update
    @point_of_service = PointOfService.find(params[:id])

     # Si le point de service est deja associé à un Organisme 
    if @point_of_service.organismes_id != nil
      @organisme_actuel = Organisme.find_by(id: @point_of_service.organismes_id)
    end 

    # Si on procede a la mise a jour du point de service
    if @point_of_service.update_attributes(point_of_service_params)
        @organisme = Organisme.find_by(id: @point_of_service.organismes_id)

        # Si l'ID n'est associé avec aucuns Organismes de la DB
        if @organisme == nil && @point_of_service.organismes_id != nil
          flash[:danger] = "Il n'existe pas d'Organisme avec l'ID #{@point_of_service.organismes_id}"
          redirect_to edit_point_of_service_path  
        else 

          # Si l'ID Organisme a été changé pour être associé à un autre Organisme
          if @point_of_service.organismes_id != nil 
            if @organisme_actuel != @organisme && @organisme_actuel != nil
               @organisme_actuel.stop_following(@point_of_service)
            end

          # On ajoute le Point de Service a l'Organisme 
          @organisme.follow(@point_of_service)

          # Si la case ID Organisme a été effacée et laissée vide, on retire le Point de Service de l'Organisme 
          elsif @point_of_service.organismes_id == nil && @organisme_actuel != nil
            @organisme_actuel.stop_following(@point_of_service)
          end

          flash[:success] = "Point de service mis à jour"
          redirect_to current_point_of_service
        end  
    else
      render 'edit'
    end
  end

  #****************************
  # Supprimer Point de Service
  #****************************
  def destroy

    # Supression de l'organisme
    point_of_service.find(params[:id]).destroy
    flash[:success] = "Point de service supprimé"

    # Retourne sur la liste des points de services
    redirect_to point_of_services_path
  end

  #*****************************************
  # Page: Ajouter ou Retirer Local
  #*****************************************
  def ajouter_retirer_local
    @point_of_service = PointOfService.find(params[:id])
    @un_locals = UnLocal.where(activated: true).paginate(page: params[:page])
  end

  #****************************
  # Ajouter Local
  #****************************
  def ajouter

    @point_of_service = PointOfService.find(params[:point_of_service_id]) 
    @un_local = UnLocal.find(params[:un_local_id])

    # Si on souhaite ajouter un local et qu'il est deja avec un autre Point de service.
    if @un_local.point_of_services_id != nil

        # On retire le local actuel pour permettre un nouvel ajout a un autre point de service
        @point_of_service = PointOfService.find_by(id: @un_local.point_of_services_id)
        @point_of_service.stop_following(@un_local)
    end  

      # On associe le local avec le point de service et on met a jour
      @point_of_service = PointOfService.find(params[:point_of_service_id]) 
      @point_of_service.follow(@un_local)
      @un_local.update_column(:point_of_services_id, current_point_of_service.id)


    flash[:success] = "Vous avez ajouté le local #{@un_local.nom} au point de service #{@point_of_service.nom}"
    redirect_to ajouter_retirer_local_point_of_service_path(@point_of_service)
  end

  #****************************
  # Retirer Local
  #****************************
  def retirer

    @point_of_service = PointOfService.find(params[:point_of_service_id]) 
    @un_local = UnLocal.find(params[:un_local_id])

    # Le point de service retire un local et on met a jour l'ID
    @point_of_service.stop_following(@un_local)
    @un_local.update_column(:point_of_services_id, nil)

    flash[:warning] = "Vous avez retiré le local #{@un_local.nom} du point de service #{@point_of_service.nom}"
    redirect_to ajouter_retirer_local_point_of_service_path(@point_of_service)
  end

  #**************************
  # Encrypter
  #**************************
    def encrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').encrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = cipher.update(self) + cipher.final

      s.unpack('H*')[0].upcase
    end
  
  #**************************
  # Decrypter
  #**************************
    def decrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').decrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = [self].pack("H*").unpack("C*").pack("c*")

      cipher.update(s) + cipher.final
    end

  private

  #*****************************
  # Parametre Point de Service
  #*****************************

  def point_of_service_params
    params.require(:point_of_service).permit(:nom, :email, :tel, :fax, :no_civique,:rue,:ville,:province,:code_postal, :organismes_id)
  end
end

app/helpers/point_of_services_helper.rb
module PointOfServicesHelper
end

app/views/point_of_services/_point_of_service.html.erb
<tr>
<% if current_page?(point_of_services_path) %>

  <td><%= point_of_service.id %></td>
  <td><%= link_to point_of_service.nom, point_of_service %></td>
  <td><%= point_of_service.tel %></td>
  <td><%= point_of_service.email %></td>
  <td><%= point_of_service.no_civique %> <%= point_of_service.rue %>, <%= point_of_service.ville %></td>
  <td><%= point_of_service.organismes_id %></td>

  <% if current_user.role == 'directeur' %>

      <td><%= link_to "modifier", edit_point_of_service_path(point_of_service) %></td>
      <td><%= link_to "supprimer", point_of_service, method: :delete, data: { confirm: "Êtes-vous certain ?" } %></td>    

    <% else %>

        <td></td>
        <td></td>

    <% end %>

<% elsif current_page?(ajouter_retirer_point_service_organisme_path) %>   

      <td><%= point_of_service.id %></td>
      <td><%= link_to point_of_service.nom, point_of_service %></td>
      <td><%= point_of_service.tel %></td>
      <td><%= point_of_service.email %></td>
      <td><%= point_of_service.no_civique %> <%= point_of_service.rue %>, <%= point_of_service.ville %></td>
      <td><%= point_of_service.organismes_id %></td>

      <% if point_of_service.followed_by?(current_organisme) %>

        <td><%= link_to "Retirer", {controller: 'organismes', action: 'retirer', organisme_id: current_organisme.id, point_of_service_id: point_of_service.id} %></td>
        <td></td>

      <% else %>

        <td></td>
        <td><%= link_to "Ajouter", {controller: 'organismes', action: 'ajouter', organisme_id: current_organisme.id, point_of_service_id: point_of_service.id} %></td>

      <% end %>

<% elsif current_page?(organisme_path) %>

  <% if point_of_service.followed_by?(current_organisme) %>   

      <td><%= point_of_service.id %></td>
      <td><%= link_to point_of_service.nom, point_of_service %></td>
      <td><%= point_of_service.tel %></td>
      <td><%= point_of_service.email %></td>
      <td><%= point_of_service.no_civique %> <%= point_of_service.rue %>, <%= point_of_service.ville %></td>
      <td><%= point_of_service.organismes_id %></td>
      <td></td>
      <td></td>
    
  <% end %>

<% elsif current_page?(un_local_path) %>

  <% if current_un_local.followed_by?(point_of_service) %>   

      <td><%= point_of_service.id %></td>
      <td><%= link_to point_of_service.nom, point_of_service %></td>
      <td><%= point_of_service.tel %></td>
      <td><%= point_of_service.email %></td>
      <td><%= point_of_service.no_civique %> <%= point_of_service.rue %>, <%= point_of_service.ville %></td>
      <td><%= point_of_service.organismes_id %></td>
      <td></td>
      <td></td>
    
  <% end %>
<% end %>
</tr>

app/views/point_of_services/ajouter_retirer_local.html.erb
<% provide(:title, 'ajouter_retirer_local') %>
<br/>
<div class="row">
	<h1>Ajouter / Retirer un Local</h1>
	<hr>
	<hr>
  <aside class="columnbtn>
	<%= button_to "Retourner au Point de Service", @point_of_service , class: "btn btn-primary", method: :get %>
</aside>
</div>
<br/>
<%= link_to "Creer nouveau Local", new_un_local_path %>
<%= render template: 'un_locals/index' %>

app/views/point_of_services/edit.html.erb
<% provide(:title, "Edit point of service") %>
<h1>Modifier le point de service</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@point_of_service) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

        <div id="main-container" class="container">
        <div id="Info Point de Service" class="col-md-6">

        <h1><a>Information</a></h1>

        <%= f.label :nom %>
        <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

        <%= f.label :tel %>
        <%= f.telephone_field :tel, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :fax %>
        <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>
        </div>
        <div id="Adresse Point de Service" class="col-md-6">

        <h1><a>Adresse</a></h1>

        <%= f.label :no_civique %>
        <%= f.text_field :no_civique, class: 'form-control', placeholder: '123' %>

        <%= f.label :rue %>
        <%= f.text_field :rue, class: 'form-control' , placeholder: 'Une Rue'%>

        <%= f.label :ville %>
        <%= f.text_field :ville, class: 'form-control', placeholder: 'Ville' %>

        <%= f.label :province %>
        <%= f.collection_select :province, PointOfService::PROVINCES, :to_s, :humanize %>

        <%= f.label :code_postal %>
        <%= f.text_field :code_postal, class: 'form-control', placeholder: 'A1B 2C3' %>

        </div>
    </div>

    <%= f.label "Si vous connaissez l'ID de l'Organisme" %>
    <%= f.number_field :organismes_id, class: 'form-control' %>

      <%= f.submit "Sauvegarder les changements", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/point_of_services/index.html.erb
<% provide(:title, 'Tous les points de services') %>
<div class="container">

  <% if current_page?(point_of_services_path) %>
    
    <h1>Tous les Points de Services</h1>
  
  <%= form_tag(point_of_services_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Nom ou Email" %>
    <%= submit_tag "Recherche", class: "btn btn-primary", :email => nil %>
  <% end %>
<% end %>
  <br/>

  <table class="table table-striped">
    <tr>
      <th>ID</th>
      <th>Nom</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Adresse</th>
      <th>ID Org.</th>
      <th></th>
      <th></th>

    <% if current_page?(point_of_services_path) %>
      <% if @point_of_services.present? %>
        <%= render @point_of_services %>
      <% else %>
        <p>Il n'y a pas de Points de Services contenant l'information : <%= params[:search] %>.</p>
      <% end %>
    <% else %>
        <%= render @point_of_services %>
    <% end %>
    </tr>
  </table>
</div>

app/views/point_of_services/new.html.erb
<% provide(:title, 'creerpointofservice') %>
<h1>Créer un nouveau point de service</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@point_of_service) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div id="main-container" class="container">
        <div id="Info Point de Service" class="col-md-6">

        <h1><a>Information</a></h1>

        <%= f.label :nom %>
        <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

        <%= f.label :tel %>
        <%= f.telephone_field :tel, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :fax %>
        <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>
        </div>
        <div id="Adresse Point de Service" class="col-md-6">

        <h1><a>Adresse</a></h1>

        <%= f.label :no_civique %>
        <%= f.text_field :no_civique, class: 'form-control', placeholder: '123' %>

        <%= f.label :rue %>
        <%= f.text_field :rue, class: 'form-control' , placeholder: 'Une Rue'%>

        <%= f.label :ville %>
        <%= f.text_field :ville, class: 'form-control', placeholder: 'Ville' %>

        <%= f.label :province %>
        <%= f.collection_select :province, PointOfService::PROVINCES, :to_s, :humanize %>

        <%= f.label :code_postal %>
        <%= f.text_field :code_postal, class: 'form-control', placeholder: 'A1B 2C3' %>

        </div>
    </div>

    <%= f.label "Si vous connaissez l'ID de l'Organisme" %>
    <%= f.number_field :organismes_id, class: 'form-control' %>

    <%= f.submit "Créer un point de service", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/point_of_services/show.html.erb
<% provide(:title, @point_of_service.nom) %>

<div class="row">
  <h1>Point de service</h1>
  <hr>
  <hr>
  <aside class="col-md-12">
    <section>

      <div id="Nom" class="column">
        <h1>
          <font size="6">
            <strong>Nom : <a><%= @point_of_service.nom %></a></strong>
          </font>
        </h1>
        <font size="5">
          <strong>ID Point de Service : <a><%= @point_of_service.id %></a></strong>
        </font>
        <br/>
        <% if current_user.role == 'directeur' %>
          <%= link_to "Modifier Point de Service", edit_point_of_service_path(@point_of_service) %>
        <% end %>
      </div>

      <div id="Contact" class="column">
        <h1>
          <font size="5">
            <strong>Contact</strong>
          </font>
        </h1>
        <br/>
        <font size="2">
          <h1>Email : <a> <%= @point_of_service.email %> </a></h1>
          <h1>Tel. : <a> <%= @point_of_service.tel %> </a></h1>
          <h1>Fax : <a> <%= @point_of_service.fax %> </a></h1>
        </font>
      </div>

      <div id="Adresse" class="column">
        <h1>
          <font size="5">
            <strong>Adresse</strong>
          </font>
        </h1>
        <br/>
        <font size="2">
          <h1>No. : <a> <%= @point_of_service.no_civique %> </a></h1>
          <h1>Rue : <a> <%= @point_of_service.rue %> </a></h1>
          <h1>Ville: <a> <%= @point_of_service.ville %> </a></h1>
          <h1>Province : <a> <%= @point_of_service.province %> </a></h1>
          <h1>Code postal : <a> <%= @point_of_service.code_postal %> </a></h1>
          <br/>
        </font>
      </div>

      <div id="Relations" class="column">
        <hr>
        <h1>
          <font size="5">
            <strong>
              Les Locaux ( <%= @voslocaux %> )
            </strong>
          </font>
        </h1>
        <br/>

        <dev class="columnbtn">
          <%= button_to "Ajouter/Retirer Local", ajouter_retirer_local_point_of_service_path(@point_of_service), class: "btn btn-primary", method: :get %>
        </dev>
        <br/>
        <%= render template: 'un_locals/index' %>
        <hr>
        <h1>
          <font size="5">
            <strong>Appartient a l'Organisme : </strong>
          </font>
        </h1>
        <%= render template: 'organismes/index' %>

        <hr>
        <h1>
          <font size="5">
            <strong>Activite</strong>
          </font>
        </h1>
        <br/>
        <font size="2">
          <h1>Actif depuis : <a> <%= @point_of_service.created_at %> </a></h1>
          <h1>Derniere Mise a Jour : <a> <%= @point_of_service.updated_at %> </a></h1>
        </font>
      </div>

    </section>
  </aside>
</div>