config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/creerreferent',           to: 'referents#new'
  get    '/creerorganisme',          to: 'organismes#new'
  get    '/creerorganismereferent',  to: 'organisme_referents#new'
  
  get    '/creerpointofservice',     to: 'point_of_services#new'
  get    '/creerunlocal',            to: 'un_locals#new'
  get    '/creerservice',            to: 'services#new'


  resources :organismes do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_org_ref, :ajouter_retirer_ref, :ajouter_retirer_point_service    
      get :organisme_id
    end
  end

  resources :organisme_referents do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_ref
    end
  end

  resources :referents do
    member do
      get :ajouter, :retirer
    end
  end

  resources :point_of_services do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_local
    end
  end

  resources :un_locals do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_service
    end
  end

  resources :services do
    member do
      get :ajouter, :retirer
    end
  end

  resources :account_activations,       only: [:edit]
  resources :password_resets,           only: [:new, :create, :edit, :update]
  resources :users

end

app/models/organisme.rb
class Organisme < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  PROVINCES = %w[Quebec Ontario Colombie-Britanique Alberta Nouvelle-Ecosse Manitoba Saskatchewan Nouveau-Brunswick Terre-Neuve ].freeze

  validates :nom, :uniqueness => true
  validates :nom, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates_presence_of :nom, :tel, :no_civique, :rue, :ville, :province, :code_postal

  before_save :downcase_email

  acts_as_follower
  acts_as_followable

  #**************************
  # Search
  #**************************
  def self.search(search)
    where("nom LIKE ?", "%#{search}%")
    where("email LIKE ?", "%#{search}%")
  end

  private

  #***********************************
  # Lettre minuscule email
  #***********************************
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/organismes_controller.rb
#**************************************************************
# CONTROLEUR ORGANISMES
#**************************************************************
require 'openssl'
class OrganismesController < ApplicationController

  #**************************
  # Liste Organisme
  #**************************
  def index
    @organismes = Organisme.where(activated: true).paginate(page: params[:page])

    # Si une recherche est lancée
    if params[:search]
      @organismes = Organisme.search(params[:search]).order("created_at DESC")
    else
      @organismes = Organisme.all.order('created_at DESC')
    end
  end

  #**************************
  # Affiche Information
  #**************************
  def show
    @organisme = Organisme.find(params[:id])

    # Affiche une liste des Referents, Points de Services et Organismes Referents 
    @referents = Referent.where(activated: true).paginate(page: params[:page])
    @point_of_services = PointOfService.where(activated: true).paginate(page: params[:page])
    @organisme_referents = OrganismeReferent.where(activated: true).paginate(page: params[:page])

    # Recupere le nombre d'objets par categorie que l'Organisme possede
    qte_objets
    
  end

  #**************************
  # Quantité Objets
  #**************************
  def qte_objets

    # Affiche les Referents, Points de Services et Organisme Referents que possede l'organisme
    @vosreferents = @organisme.follows_by_type('Referent').count
    @vospointservices = @organisme.follows_by_type('PointOfService').count
    @vosorganismereferents = @organisme.follows_by_type('OrganismeReferent').count
  end 

  #**************************
  # Nouvel Organisme
  #**************************
  def new
    @organisme = Organisme.new
  end

  #**************************
  # Creer Organisme
  #**************************
  def create
    @organisme = Organisme.new(organisme_params)

    # Confirme la creation d'un organisme
    if @organisme.save
      flash[:success] = "Organisme créé"
      redirect_to @organisme
    else
      render 'new'
    end
  end

  #**************************
  # Modifier Organisme
  #**************************
  def edit
    @organisme = Organisme.find(params[:id])
  end

  #**************************
  # Mise a jour Organisme
  #**************************
  def update
    @organisme = Organisme.find(params[:id])

    # Met a jour l'information
    if @organisme.update_attributes(organisme_params)
      flash[:success] = "Organisme mis à jour"
      redirect_to current_organisme
    else
      render 'edit'
    end
  end

  #**************************
  # Supprimer Organisme
  #**************************
  def destroy

    # Supression de l'organisme
    Organisme.find(params[:id]).destroy
    flash[:success] = "Organisme supprimé"

    # Redirige vers la liste des Organismes
    redirect_to organismes_path
  end

  #********************************************
  # Page: Ajouter ou Retirer Organisme Referent
  #********************************************
  def ajouter_retirer_org_ref
    @organisme = Organisme.find(params[:id])
    @organisme_referents = OrganismeReferent.where(activated: true).paginate(page: params[:page])
  end

  #*****************************************
  # Page: Ajouter ou Retirer Referent
  #*****************************************
  def ajouter_retirer_ref
    @organisme = Organisme.find(params[:id])
    @referents = Referent.where(activated: true).paginate(page: params[:page])
  end

  #********************************************
  # Page: Ajouter ou Retirer Point de Service
  #********************************************
  def ajouter_retirer_point_service
    @organisme = Organisme.find(params[:id])
    @point_of_services = PointOfService.where(activated: true).paginate(page: params[:page])
  end   


  #****************************************************************************************
  #                               Ajouter Objets
  #****************************************************************************************     

  #*********************************
  # Ajouter un Objet a l'Organisme
  #*********************************
  def ajouter

    @organisme = Organisme.find(params[:organisme_id]) 

    # Pour l'ajout d'un Organisme Referent a l'Organisme
    if params[:organisme_referent_id]
      ajouter_organisme_referent
    
    # Pour l'ajout d'un Referent a l'Organisme
    elsif params[:referent_id]
      ajouter_referent

    # Pour l'ajout d'un Point de Service a l'Organisme  
    elsif params[:point_of_service_id]
       ajouter_point_service
    end   
  end

  #*********************************
  # Ajout d'un Organisme Referent
  #*********************************
  def ajouter_organisme_referent

    # Recupere l'Organisme Referent' et l'ajoute a Organisme
    @organisme_referent = OrganismeReferent.find(params[:organisme_referent_id])
    processus_ajouter(@organisme_referent)
      
    flash[:success] = "Vous avez ajouté l'organisme referent #{@organisme_referent.nom} à l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_org_ref_organisme_path(@organisme)
  end  

  #*********************************
  # Ajout d'un Referent
  #*********************************
  def ajouter_referent

    # On associe le Referent avec l'Organisme
    @organisme = Organisme.find(params[:organisme_id]) 
    @referent = Referent.find(params[:referent_id])
    @organisme.follow(@referent)

    flash[:success] = "Vous avez ajouté le referent #{@referent.prenom} à l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_ref_organisme_path(@organisme) 
  end 

  #*********************************
  # Ajout d'un Point de Service
  #*********************************
  def ajouter_point_service

    # Recupere le Point de Service et l'ajoute a Organisme
    @point_of_service = PointOfService.find(params[:point_of_service_id])
    processus_ajouter(@point_of_service)

    flash[:success] = "Vous avez ajouté le point de service #{@point_of_service.nom} à l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_point_service_organisme_path(@organisme) 
  end  

  #*********************************
  # Processus d'Ajout Universel
  #*********************************
  def processus_ajouter(objet)

      # Si on souhaite ajouter l'objet et qu'il est deja avec un autre Organisme.
      if objet.organismes_id != nil

        # Recupere l'ID Organisme et retire l'objet actuel 
        @un_organisme = Organisme.find_by(id: objet.organismes_id)
        @un_organisme.stop_following(objet)
      end  

      # Ajoute l'objet a l'Organisme et met a jour son organismes_id
      @organisme = Organisme.find(params[:organisme_id]) 
      @organisme.follow(objet)
      objet.update_column(:organismes_id, current_organisme.id)
  end   


  #****************************************************************************************
  #                               Retirer Objets
  #****************************************************************************************

  #*********************************
  # Retirer un Objet a l'Organisme
  #*********************************
  def retirer

    # Pour retirer un Organisme Referent a l'Organisme
    if params[:organisme_referent_id]
      retirer_organisme_referent
    
    # Pour retirer un Referent a l'Organisme
    elsif params[:referent_id]
      retirer_referent

    # Pour retirer un Point de Service a l'Organisme  
    elsif params[:point_of_service_id]
      retirer_point_service    
    end   
  end

  #*********************************
  # Retirer un Organisme Referent
  #*********************************
  def retirer_organisme_referent

    # Recupere l'Organisme Referent et le retire de l'Organisme
    @organisme_referent = OrganismeReferent.find(params[:organisme_referent_id]) 
    processus_retirer(@organisme_referent)
      
    flash[:warning] = "Vous avez retiré l'organisme referent #{@organisme_referent.nom} de l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_org_ref_organisme_path(@organisme)
  end

  #*********************************
  # Retirer un Referent
  #*********************************
  def retirer_referent

    # Recupere le Referent et le retire de l'Organisme
    @referent = Referent.find(params[:referent_id])
    processus_retirer(@referent)

    flash[:warning] = "Vous avez retiré le referent #{@referent.prenom} de l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_ref_organisme_path(@organisme) 
  end
  
  #*********************************
  # Retirer un Point de Service
  #*********************************
  def retirer_point_service

    # Recupere le Point de Service et le retire de l'Organisme
    @point_of_service = PointOfService.find(params[:point_of_service_id])
    processus_retirer(@point_of_service)

    flash[:warning] = "Vous avez retiré le point de service #{@point_of_service.nom} de l'organisme #{@organisme.nom}"
    redirect_to ajouter_retirer_point_service_organisme_path(@organisme)
  end  

  #*********************************
  # Processus Retirer Universel
  #*********************************
  def processus_retirer(objet)

    # On defait l'association entre l'objet et l'Organisme et met a jour son organismes_id
    @organisme = Organisme.find(params[:organisme_id])
    @organisme.stop_following(objet)
    objet.update_column(:organismes_id, nil)
  end  

  #**************************
  # Encrypter
  #**************************
    def encrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').encrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = cipher.update(self) + cipher.final

      s.unpack('H*')[0].upcase
    end
  
  #**************************
  # Decrypter
  #**************************
    def decrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').decrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = [self].pack("H*").unpack("C*").pack("c*")

app/helpers/organismes_helper.rb
#**************************************************************
# SUPPORT ORGANISMES
#**************************************************************
module OrganismesHelper

end

app/views/organismes/_organisme.html.erb
<tr>
<% if current_page?(organismes_path) %>

  <td><%= organisme.id %></td>
  <td><%= link_to organisme.nom, organisme %></td>
  <td><%= organisme.tel %></td>
  <td><%= organisme.email %></td>
  <td><%= organisme.no_civique %> <%= organisme.rue %>, <%= organisme.ville %>, <%= organisme.province %></td>
  <td><%= organisme.est_actif %></td>

  <% if current_user.role == 'directeur' %>

      <td><%= link_to "modifier", edit_organisme_path(organisme) %></td>
      <td><%= link_to "supprimer", organisme, method: :delete, data: { confirm: "Êtes-vous certain ?" } %></td>
  <% else %>

      <td></td>
      <td></td>
  
  <% end %>    

<% elsif current_page?(organisme_referent_path) %>
  <% if current_organisme_referent.followed_by?(organisme) %>

      <td><%= organisme.id %></td>
      <td><%= link_to organisme.nom, organisme %></td>
      <td><%= organisme.tel %></td>
      <td><%= organisme.email %></td>
      <td><%= organisme.no_civique %> <%= organisme.rue %>, <%= organisme.ville %></td>
      <td><%= organisme.est_actif %></td>
      <td></td>
      <td></td>
      
    <% end %>

<% elsif current_page?(referent_path) %>
  <% if current_referent.followed_by?(organisme) %>

      <td><%= organisme.id %></td>
      <td><%= link_to organisme.nom, organisme %></td>
      <td><%= organisme.tel %></td>
      <td><%= organisme.email %></td>
      <td><%= organisme.no_civique %> <%= organisme.rue %>, <%= organisme.ville %></td>
      <td><%= organisme.est_actif %></td>
      <td></td>
      <td></td>
      
    <% end %> 

<% elsif current_page?(point_of_service_path) %>
  <% if current_point_of_service.followed_by?(organisme) %>

      <td><%= organisme.id %></td>
      <td><%= link_to organisme.nom, organisme %></td>
      <td><%= organisme.tel %></td>
      <td><%= organisme.email %></td>
      <td><%= organisme.no_civique %> <%= organisme.rue %>, <%= organisme.ville %></td>
      <td><%= organisme.est_actif %></td>
      <td></td>
      <td></td>
      
    <% end %>        
<% end %>
</tr>

app/views/organismes/ajouter_retirer_org_ref.html.erb
<% provide(:title, 'ajouter_retirer_org_ref') %>
<br/>
<div class="row">
  <aside class="columnbtn">
<%= button_to "Retourner vers l'Organisme", @organisme , class: "btn btn-primary", method: :get %>
</aside>
</div>
<br/>
<%= link_to "Creer nouvel Organisme Referent", new_organisme_referent_path %>

<%= render template: 'organisme_referents/index' %>

app/views/organismes/ajouter_retirer_point_service.html.erb
<% provide(:title, 'ajouter_retirer_point_service') %>
<br/>
<div class="row">

	<h1>Ajouter / Retirer un Point de Service</h1>
	<hr>
	<hr>

  <aside class="columnbtn">
	<%= button_to "Retourner vers l'Organisme", @organisme , class: "btn btn-primary", method: :get %>
</aside>
</div>
<br/>
<%= link_to "Creer nouveau Point de Service", new_point_of_service_path %>
<%= render template: 'point_of_services/index' %>

app/views/organismes/ajouter_retirer_ref.html.erb
<% provide(:title, 'ajouter_retirer_ref') %>
<br/>
<div class="row">
  <aside class="columnbtn">
	<%= button_to "Retourner vers l'Organisme", @organisme , class: "btn btn-primary", method: :get %>
</aside>
</div>
<br/>
<%= link_to "Creer nouveau Referent", new_referent_path %>

<%= render template: 'referents/index' %>

app/views/organismes/edit.html.erb
<% provide(:title, "Edit organisme") %>
<h1>Modifier Organisme</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@organisme) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

      <div id="main-container" class="container">
            <div id="Info Organisme" class="col-md-6">

            <h1><a>Information</a></h1>

            <%= f.label :nom %>
            <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

            <%= f.label :tel %>
            <%= f.telephone_field :tel, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

            <%= f.label :fax %>
            <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>

        </div>
        <div id="Adresse" class="col-md-6">

            <h1><a>Adresse</a></h1>

            <%= f.label :no_civique %>
            <%= f.text_field :no_civique, class: 'form-control', placeholder: '123' %>

            <%= f.label :rue %>
            <%= f.text_field :rue, class: 'form-control' , placeholder: 'Une Rue'%>

            <%= f.label :ville %>
            <%= f.text_field :ville, class: 'form-control', placeholder: 'Ville' %>

            <%= f.label :province %>
            <%= f.collection_select :province, Organisme::PROVINCES, :to_s, :humanize %>

            <%= f.label :code_postal %>
            <%= f.text_field :code_postal, class: 'form-control', placeholder: 'A1B 2C3' %>
        </div>
    </div>


        <%= f.submit "Sauvegarder les changements", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/organismes/index.html.erb
<% provide(:title, 'Tous les Organismes') %>
<div class="container">
  <% if current_page?(organismes_path) %>

    <h1>Repertoire des Organismes</h1>
    <hr>
    <hr>
    <br/>
    <%= form_tag(organismes_path, :method => "get", id: "search-form") do %>

        <%= text_field_tag :search, params[:search], placeholder: "Nom ou Email" %>
        <%= submit_tag "Recherche", class: "btn btn-primary", :email => nil %>

    <% end %>
  <% end %>
  <br/>
  <br/>

  <table class="table table-striped">
    <tr>
      <th>ID</th>
      <th>Nom</th>
      <th>Telephone</th>
      <th>Email</th>
      <th>Adresse</th>
      <th>Actif</th>
      <th></th>
      <th></th>

      <% if current_page?(organisme_referents_path) %>
        <% if @organismes.present? %>
          <%= render @organismes %>
        <% else %>
          <p>Il n'y a pas d'Organisme contenant l'information : <%= params[:search] %>.</p>
        <% end %>
      <% else %>
        <%= render @organismes %>
      <% end %>
    </tr>
  </table>
</div>

app/views/organismes/new.html.erb
<% provide(:title, 'creerorganisme') %>
<h1>Créer un nouvel Organisme </h1>
<hr>
<hr>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@organisme) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div id="main-container" class="container">

            <div id="Info Organisme" class="column2">
            <h1><a>Information</a></h1>

            <%= f.label :nom %>
            <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

            <%= f.label :tel %>
            <%= f.telephone_field :tel, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

            <%= f.label :fax %>
            <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>

        </div>
        <div id="Adresse" class="column2">

            <h1><a>Adresse</a></h1>

            <%= f.label :no_civique %>
            <%= f.text_field :no_civique, class: 'form-control', placeholder: '123' %>

            <%= f.label :rue %>
            <%= f.text_field :rue, class: 'form-control' , placeholder: 'Une Rue'%>

            <%= f.label :ville %>
            <%= f.text_field :ville, class: 'form-control', placeholder: 'Ville' %>

            <%= f.label :province %>
            <%= f.collection_select :province, Organisme::PROVINCES, :to_s, :humanize %>

            <%= f.label :code_postal %>
            <%= f.text_field :code_postal, class: 'form-control', placeholder: 'A1B 2C3' %>
        </div>
    </div>
      <br/>
      <dev class="columnbtn">
        <%= f.submit "Créer organisme", class: "btn btn-primary" %>
      </dev>
    <% end %>
  </div>
</div>

app/views/organismes/show.html.erb
<% provide(:title, @organisme.nom) %>

<div class="row">
  <h1>Compte Organisme</h1>
  <hr>
  <hr>

  <aside class="col-md-12">
    <section>
      <div id="Nom" class="column">
        <h1>
          <font size="6">
            <strong>Nom : <a><%= @organisme.nom %></a></strong>
          </font>
        </h1>
        <font size="5">
          <strong>ID organisme : <a><%= @organisme.id %></a></strong>
        </font>
        <br/>
        <% if current_user.role == 'directeur' %>
          <%= link_to "Modifier organisme", edit_organisme_path(@organisme) %>
        <% end %>
      </div>

      <div id="Contact" class="column">
        <h1>
          <font size="5">
            <strong>Contact</strong>
          </font>
        </h1>
        <br/>
        <font size="2">
          <h1>Email : <a> <%= @organisme.email %> </a></h1>
          <h1>Tel. : <a> <%= @organisme.tel %> </a></h1>
          <h1>Fax : <a> <%= @organisme.fax %> </a></h1>
        </font>
      </div>

      <div id="Adresse" class="column">
        <h1>
          <font size="5">
            <strong>Adresse</strong>
          </font>
        </h1>
        <br/>
        <font size="2">
          <h1>No. : <a> <%= @organisme.no_civique %> </a></h1>
          <h1>Rue : <a> <%= @organisme.rue %> </a></h1>
          <h1>Ville: <a> <%= @organisme.ville %> </a></h1>
          <h1>Province : <a> <%= @organisme.province %> </a></h1>
          <h1>Code postal : <a> <%= @organisme.code_postal %> </a></h1>
          <br/>
        </font>
      </div>

      <div id="Relations" class="column">

      <hr>
      <h1>
        <font size="5">
          <strong>Relations: <a>Points de Services ( <%= @vospointservices %> )</a></strong>
        </font>
      </h1>
      <br/>

      <% if current_user.role == 'directeur' %>
        <dev class="columnbtn">
          <%= button_to "Ajouter/Retirer Point de Service", ajouter_retirer_point_service_organisme_path(@organisme), class: "btn btn-primary", method: :get %>
        </dev>
      <% end %>
      <%= render template: 'point_of_services/index' %>
      <hr>
      <h1>
        <font size="5">
          <strong>Relations: <a>Referents ( <%= @vosreferents %> )</a></strong>
        </font>
      </h1>
      <br/>

      <% if current_user.role == 'coordonateur' || current_user.role == 'directeur' %>
        <dev class="columnbtn">
          <%= button_to "Ajouter/Retirer Referent", ajouter_retirer_ref_organisme_path(@organisme), class: "btn btn-primary", method: :get %>
        </dev>
      <% end %>
      <%= render template: 'referents/index' %>
      <hr>

      <h1>
        <font size="5">
          <strong>Activité</strong>
        </font>
      </h1>
      <br/>
      <font size="2">
        <h1>Actif depuis : <a> <%= @organisme.created_at %> </a></h1>
        <h1>Derniere Mise a Jour : <a> <%= @organisme.updated_at %> </a></h1>
      </font>
      </div>
    </section>
  </aside>
</div>