config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/creerreferent',           to: 'referents#new'
  get    '/creerorganisme',          to: 'organismes#new'
  get    '/creerorganismereferent',  to: 'organisme_referents#new'
  
  get    '/creerpointofservice',     to: 'point_of_services#new'
  get    '/creerunlocal',            to: 'un_locals#new'
  get    '/creerservice',            to: 'services#new'


  resources :organismes do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_org_ref, :ajouter_retirer_ref, :ajouter_retirer_point_service    
      get :organisme_id
    end
  end

  resources :organisme_referents do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_ref
    end
  end

  resources :referents do
    member do
      get :ajouter, :retirer
    end
  end

  resources :point_of_services do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_local
    end
  end

  resources :un_locals do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_service
    end
  end

  resources :services do
    member do
      get :ajouter, :retirer
    end
  end

  resources :account_activations,       only: [:edit]
  resources :password_resets,           only: [:new, :create, :edit, :update]
  resources :users

end

app/models/referent.rb
class Referent < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  RAPPORT_E_F_P = %w[N/A Email Fax Papier].freeze

  validates :pref_rapport_1, presence: true
  validates :pref_rapport_2, presence: true
  validates :pref_rapport_3, presence: true
  
  validates :email, :uniqueness => true
  validates :nom, presence: true, length: { maximum: 50 }
  validates :titre, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  validates_presence_of :nom, :prenom, :titre, :tel_bureau, :email

  acts_as_follower
  acts_as_followable

  #**************************
  # Recherche Referent
  #**************************
  def self.search(search)

      recherche = "%#{search}%"
      where("nom LIKE ? OR prenom LIKE ? OR titre LIKE ?
           OR tel_bureau LIKE ? OR organismes_id LIKE ?", 
            recherche, recherche, recherche,
            recherche, recherche)
  end


end

app/controllers/referents_controller.rb
#**************************************************************
# CONTROLEUR ORGANISMES REFERENTS
#**************************************************************
require 'openssl'
class ReferentsController < ApplicationController

  #**************************
  # Liste Referent
  #**************************
  def index
    @referents = Referent.where(activated: true).paginate(page: params[:page])

    # Si une recherche est lancée
    if params[:search]
        @referents = Referent.search(params[:search]).order("created_at DESC")
    else
      @referents = Referent.all.order('created_at DESC')
    end
  end

  #**************************
  # Afficher info Referent
  #**************************
  def show
    @referent = Referent.find(params[:id])

    # Permet d'afficher l'information complet d'un Organisme associé au Referent
    @organismes = Organisme.where(activated: true).paginate(page: params[:page])

  end

  #**************************
  # Nouveau Referent
  #**************************
  def new
    @referent = Referent.new
  end

  #**************************
  # Creer Referent
  #**************************
  def create
    @referent = Referent.new(referent_params)

    # Si l'utilisateur confirme la creation d'un referent
    if @referent.save

      flash[:success] = "Referent créé"
      redirect_to @referent
    else
      render 'new'
    end
  end

  #**************************
  # Modifier Referent
  #**************************
  def edit
    @referent = Referent.find(params[:id])
  end

  #**************************
  # Mise a jour Referent
  #**************************
  def update
    @referent = Referent.find(params[:id])
    if @referent.update_attributes(referent_params)
      flash[:success] = "Referent mis à jour"
      redirect_to current_referent
    else
      render 'edit'
    end
  end

  #**************************
  # Supprimer Referent
  #**************************
  def destroy

    # Supression du referent
    Referent.find(params[:id]).destroy
    flash[:success] = "Referent supprimé"
    redirect_to referents_path
  end

  #**************************
  # Ajouter (Usage futur)
  #**************************
  def ajouter
  end

  #**************************
  # Retirer (Usage futur)
  #**************************
  def retirer
  end

  #**************************
  # Encrypter
  #**************************
    def encrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').encrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = cipher.update(self) + cipher.final

      s.unpack('H*')[0].upcase
    end
  
  #**************************
  # Decrypter
  #**************************
    def decrypt(key)
      cipher = OpenSSL::Cipher::Cipher.new('DES-EDE3-CBC').decrypt
      cipher.key = Digest::SHA1.hexdigest key
      s = [self].pack("H*").unpack("C*").pack("c*")

      cipher.update(s) + cipher.final
    end

  private

  #**************************
  # Parametre Referent
  #**************************
  def referent_params
    params.require(:referent).permit(:nom, :prenom, :titre, :tel_bureau, :tel_cell, :fax, :email,:organismes_id, :pref_rapport_1, :pref_rapport_2, :pref_rapport_3)
  end
end

app/helpers/referents_helper.rb
#**************************************************************
# SUPPORT REFERENTS
#**************************************************************
module ReferentsHelper
end

app/views/referents/_referent.html.erb
<tr>
<% if current_page?(referents_path) %>

		<td><%= referent.id %></td>
		<td><%= link_to referent.prenom, referent %></td>
		<td><%= link_to referent.nom, referent %></td>
		<td><%= referent.titre %></td>
		<td><%= referent.tel_bureau %></td>
		<td><%= referent.email %></td>

	<% if current_user.role == 'coordonateur' || current_user.role == 'directeur' %>

		<td><%= link_to "modifier", edit_referent_path(referent) %></td>
		<td><%= link_to "supprimer", referent, method: :delete, data: { confirm: "Êtes-vous certain ?" } %></td>

	<% else %>

        <td></td>
        <td></td>

    <% end %>

<% elsif current_page?(ajouter_retirer_ref_organisme_path) %>

		<td><%= referent.id %></td>
		<td><%= link_to referent.prenom, referent %></td>
		<td><%= link_to referent.nom, referent %></td>
		<td><%= referent.titre %></td>
		<td><%= referent.tel_bureau %></td>
		<td><%= referent.email %></td>

    	<% if referent.followed_by?(current_organisme) %>

		    <td><%= link_to "Retirer", {controller: 'organismes', action: 'retirer', organisme_id: current_organisme.id, referent_id: referent.id} %></td>
		    <td></td>

		<% else %>

			<td></td>
		    <td><%= link_to "Ajouter", {controller: 'organismes', action: 'ajouter', organisme_id: current_organisme.id, referent_id: referent.id} %></td>

		<% end %>

<% elsif current_page?(ajouter_retirer_ref_organisme_referent_path) %>

		<td><%= referent.id %></td>
		<td><%= link_to referent.prenom, referent %></td>
		<td><%= link_to referent.nom, referent %></td>
		<td><%= referent.titre %></td>
		<td><%= referent.tel_bureau %></td>
		<td><%= referent.email %></td>

    	<% if referent.followed_by?(current_organisme_referent) %>

		    <td><%= link_to "Retirer", {controller: 'organisme_referents', action: 'retirer', organisme_referent_id: current_organisme_referent.id, referent_id: referent.id} %></td>
		    <td></td>

		<% else %>

			<td></td>
		    <td><%= link_to "Ajouter", {controller: 'organisme_referents', action: 'ajouter', organisme_referent_id: current_organisme_referent.id, referent_id: referent.id} %></td>

		<% end %>
		
<% elsif current_page?(organisme_path) %>

	<% if referent.followed_by?(current_organisme) %>

		<td><%= referent.id %></td>
		<td><%= link_to referent.prenom, referent %></td>
		<td><%= link_to referent.nom, referent %></td>
		<td><%= referent.titre %></td>
		<td><%= referent.tel_bureau %></td>
		<td><%= referent.email %></td>
        <th></th>
        <th></th>
		
	<% end %>

<% elsif current_page?(organisme_referent_path) %>

	<% if referent.followed_by?(current_organisme_referent) %>

		<td><%= referent.id %></td>
		<td><%= link_to referent.prenom, referent %></td>
		<td><%= link_to referent.nom, referent %></td>
		<td><%= referent.titre %></td>
		<td><%= referent.tel_bureau %></td>
		<td><%= referent.email %></td>
        <th></th>
        <th></th>
		
	<% end %>	  		  
<% end %>
</tr>

app/views/referents/edit.html.erb
<% provide(:title, "Edit referent") %>
<h1>Modifier Referent</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@referent) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div id="main-container" class="container">
        <div id="Info Referent" class="col-md-6">

        <h1><a>Information</a></h1>

        <%= f.label :prenom %>
        <%= f.text_field :prenom, class: 'form-control', placeholder: 'prenom' %>

        <%= f.label :nom %>
        <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

        <%= f.label :titre %>
        <%= f.text_field :titre, class: 'form-control', placeholder: 'titre' %>

    </div>
    <div id="Contact Referent" class="col-md-6">

        <h1><a>Contact</a></h1>

        <%= f.label 'Téléphone de Bureau' %>
        <%= f.text_field :tel_bureau, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label 'Téléphone Cellulaire' %>
        <%= f.text_field :tel_cell, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :fax %>
        <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>
    </div>
</div>
    <div id="Preference Referent" class="col-md-6 col-md-offset-3">
    <h1><a>Preferences</a></h1>

    <%= f.label 'Réception rapport no 1' %>
    <%= f.collection_select :pref_rapport_1, Referent::RAPPORT_E_F_P, :to_s, :humanize %>

    <%= f.label 'Réception rapport no 2' %>
    <%= f.collection_select :pref_rapport_2, Referent::RAPPORT_E_F_P, :to_s, :humanize %>

    <%= f.label 'Réception rapport no 3' %>
    <%= f.collection_select :pref_rapport_3, Referent::RAPPORT_E_F_P, :to_s, :humanize %>
    <br/>
    <br/>
    </div>
        <%= f.submit "Sauvegarder les changements", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/referents/index.html.erb
<% provide(:title, 'Tous Referents') %>
<div class="container">

  <% if current_page?(referents_path) %>

    <h1>Tous les Referents</h1>

    <%= form_tag(referents_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Prenom ou Nom ou Titre ou Telephone_Bureau ou ID Organisme" %>
      <%= submit_tag "Recherche", class: "btn btn-primary", :email => nil %>
    <% end %>
  <% end %>
  <br/>
  <br/>
  <table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Prenom</th>
    <th>Nom</th>
    <th>Titre</th>
    <th>Tel. bureau</th>
    <th>Email</th>
    <th></th>
    <th></th>

  <% if current_page?(referents_path) %>
    <% if @referents.present? %>
      <%= render @referents %>
    <% else %>
      <p>Il n'y a pas de Referents contenant l'information : <%= params[:search] %></p>
    <% end %>
  <% else %>
      <%= render @referents %>
  <% end %>  
  </tr>
</table>
</div>

app/views/referents/new.html.erb
<% provide(:title, 'creerreferent') %>
<h1>Créer un nouveau referent</h1>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@referent) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div id="main-container" class="container">
        <div id="Info Referent" class="col-md-6">

        <h1><a>Information</a></h1>

        <%= f.label :prenom %>
        <%= f.text_field :prenom, class: 'form-control', placeholder: 'prenom' %>

        <%= f.label :nom %>
        <%= f.text_field :nom, class: 'form-control', placeholder: 'nom' %>

        <%= f.label :titre %>
        <%= f.text_field :titre, class: 'form-control', placeholder: 'titre' %>

    </div>
    <div id="Contact Referent" class="col-md-6">

        <h1><a>Contact</a></h1>

        <%= f.label 'Téléphone de Bureau' %>
        <%= f.text_field :tel_bureau, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label 'Téléphone Cellulaire' %>
        <%= f.text_field :tel_cell, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :fax %>
        <%= f.telephone_field :fax, class: 'form-control', placeholder: 'xxx-xxx-xxxx' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'exemple@email.com' %>
    </div>
</div>
    <div id="Preference Referent" class="col-md-6 col-md-offset-3">
    <h1><a>Preferences</a></h1>

    <%= f.label 'Réception rapport no 1' %>
    <%= f.collection_select :pref_rapport_1, Referent::RAPPORT_E_F_P, :to_s, :humanize %>

    <%= f.label 'Réception rapport no 2' %>
    <%= f.collection_select :pref_rapport_2, Referent::RAPPORT_E_F_P, :to_s, :humanize %>

    <%= f.label 'Réception rapport no 3' %>
    <%= f.collection_select :pref_rapport_3, Referent::RAPPORT_E_F_P, :to_s, :humanize %>
    <br/>
    <br/>
    </div>
    <%= f.submit "Créer referent", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/referents/show.html.erb
<% provide(:title, @referent.prenom) %>

<div class="row">
  <h1>Compte Referent</h1>
  <aside class="col-md-12">
    <section>
      <h1>
      <br/>
      <font size="5">
        <strong>ID referent : <a><%= @referent.id %></a></strong>
      </font>  
      </h1>  
      <h1>
        <font size="6">
          <strong>
            Nom : <a><%= @referent.prenom %> <%= @referent.nom %></a>
          </strong>
        </font>
      </h1>
      <% if current_user.role == 'directeur' || current_user.role == 'coordonateur' %>
        <li><%= link_to "Modifier référent", edit_referent_path(@referent) %></li>
      <% end %>
       <br/>
      <h1>
        <font size="5">
          <strong>Titre : <a><%= @referent.titre %></a></strong>
          <br/>
          <strong>Email : <a><%= @referent.email %></a></strong>
        </font>
      </h1>
      <br/>
      <br/>
      <hr>
      <hr>
    <div id="main-container" class="container">
      <div id="Contact" class="col-md-6">
      <h1>
        <font size="5">
          <strong>Contact</strong>
        </font>
      </h1>
      <br/>
      <font size="2">
        <h1>Telephone bureau : <a> <%= @referent.tel_bureau %> </a></h1>
        <h1>Telephone cellulaire : <a> <%= @referent.tel_cell %> </a></h1>
        <h1>Fax : <a> <%= @referent.fax %> </a></h1>
      </font>
    </div>
    <div id="Preference" class="col-md-6">
      <h1>
        <font size="5">
          <strong>Preference d'envoi rapport</strong>
        </font>
      </h1>
      <br/>
      <h1>Preference no.1 : <a> <%= @referent.pref_rapport_1 %> </a></h1>
      <h1>Preference no.2 : <a> <%= @referent.pref_rapport_2 %> </a></h1>
      <h1>Preference no.3 : <a> <%= @referent.pref_rapport_3 %> </a></h1>
    </div>
  </div>
  <br/>
  <hr>
  <h1>
    <font size="5">
      <strong>Appartient aux Organismes</strong>
    </font>
  </h1> 
  <%= render template: 'organismes/index' %>
  <br/>
      <hr>
        <h1>
        <font size="5">
          <strong>Notifications</strong>
        </font>
      </h1>
      <br/>
         <font size="2">
        <h1>Actif depuis : <a> <%= @referent.created_at %> </a></h1>
        <h1>Derniere Mise a Jour : <a> <%= @referent.updated_at %> </a></h1>
      </font>
    </section>
  </aside>
</div>