config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/creerreferent',           to: 'referents#new'
  get    '/creerorganisme',          to: 'organismes#new'
  get    '/creerorganismereferent',  to: 'organisme_referents#new'
  
  get    '/creerpointofservice',     to: 'point_of_services#new'
  get    '/creerunlocal',            to: 'un_locals#new'
  get    '/creerservice',            to: 'services#new'


  resources :organismes do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_org_ref, :ajouter_retirer_ref, :ajouter_retirer_point_service    
      get :organisme_id
    end
  end

  resources :organisme_referents do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_ref
    end
  end

  resources :referents do
    member do
      get :ajouter, :retirer
    end
  end

  resources :point_of_services do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_local
    end
  end

  resources :un_locals do
    member do
      get :ajouter, :retirer
      get :ajouter_retirer_service
    end
  end

  resources :services do
    member do
      get :ajouter, :retirer
    end
  end

  resources :account_activations,       only: [:edit]
  resources :password_resets,           only: [:new, :create, :edit, :update]
  resources :users

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Information",   about_path %></li>
      <li><%= link_to "Nous joindre", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "RQRSDA", root_path, id: "logo" %>
    <% else %>
      <%= link_to "RQRSDA", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Afficher <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

              <% if current_user.role == 'directeur' %>
                <li><%= link_to "Liste Locaux", un_locals_path %></li>
                <li><%= link_to "Liste Services", services_path %></li>
                <li><%= link_to "Liste Points de services", point_of_services_path %></li>
              <% end %>

              <li class="divider"></li>

              <li><%= link_to "Liste Referents", referents_path %></li>

              <% if current_user.role == 'coordonateur' || current_user.role == 'directeur' %>
                <% if current_user.role == 'directeur' %>
                  <li><%= link_to "Liste Organismes", organismes_path %></li>
                <% end %>

                <li><%= link_to "Liste Organismes Referents", organisme_referents_path %></li>
              <% end %>

              <li class="divider"></li>

              <li><%= link_to "Liste Usagers", users_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Créer <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

              <% if current_user.role == 'directeur' %>
                <li><%= link_to "Nouveau Local", creerunlocal_path %></li>
                <li><%= link_to "Nouveau Service", creerservice_path %></li>
                <li><%= link_to "Nouveau Point de service", creerpointofservice_path %></li>
              <% end %>

              <li class="divider"></li>

              <li><%= link_to "Nouveau Referent", creerreferent_path %></li>

              <% if current_user.role == 'coordonateur' || current_user.role == 'directeur' %>
                <% if current_user.role == 'directeur' %>
                  <li><%= link_to "Nouvel Organisme", creerorganisme_path %></li>
                        <li><%= link_to "Nouveau point de service", creerpointofservice_path %></li>
                <% end %>

                <li><%= link_to "Nouvel Organisme Referent", creerorganismereferent_path %></li>

                <li class="divider"></li>
                <li><%= link_to "Nouvel Usager", signup_path %></li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to " | Votre Compte", root_path %></li>
          <li><%= link_to "Déconnexion  | ", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Acceuil", root_path %></li>
          <li><%= link_to "Plan du site", about_path %></li>
          <li><%= link_to "Connexion", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>